apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-pv
  hostPath:
    path: "/home/jenkins/jenkins-data"
