apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
#  type: LoadBalancer
  ports:
    - protocol: TCP
      name: jenkins
      port: 80
      targetPort: 8080
      nodePort: 32000
  selector:
    app: jenkins
